# Site
repository: sproogen/resume-theme
favicon: images/charly_sketch.jpg

# Content configuration version
version: 2

# Personal info
name: Carlos Flury
title: Data Scientist
email: car.flury@gmail.com
website: www.github.com/floricar/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: charlesflury_
github_username:  floricar
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: carflury
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pic_5_small.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Carlos Flury from Argentina. I am a curious Data Scientist and love working on exciting and challenging projects. Most of all: I like learning from any topic and my life is dedicated to it.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rosario Trading Board
        link: www.bcr.com.ar
        # link_text: boringcompany.com
        sub_title: Analyst and Developer
        caption: January 2019 - Present
        quote: >
          Working at the tech area of a large organization, dedicated to facilitate the agro industry in Rosario, Argentina and region near by.
        description: | # this will include new lines to allow paragraphs
            At Rosario Trading Board I've been working on three lines: on an image classification problem that we are working with deep learning models, on a integrated plan to facilitate the digital transformation indoor the company and on some Business Intelligence projects (developing reports for the end user).
      - layout: left
        title: Method Data Science
        link: www.bcr.com.ar
        # link_text: boringcompany.com
        sub_title: Community Data Scientist
        caption: November 2018 - March 2019
        quote: >
          Method Data Science is destined to connect small to median companies with data scientists working on their first real-world projects.
        description: | # this will include new lines to allow paragraphs
            At Method Data Science, I was lucky to found myself in a global community of professionals in which we were teamed up for solving different kind of projects. Me and the team "Newton" (we were called) worked on a kaggle challenge, a prediction on knee illnes and an association problem to target social media users.
      - layout: left
        title: Inteligencia Analitica
        link: www.inteligenciaanalitica.com
        # link_text: boringcompany.com
        sub_title: 
        caption: November 2017 - November 2018
        quote: >
          Inteligencia Analitica is a end-to-end consultant company specialized on Business Intelligence challenges. From reporting and analytics to ETL processes development.
        description: | # this will include new lines to allow paragraphs
            At Inteligencia Analitica I worked side by side with a customer from the bank industry. I was primarily asked to develop multiples static reports and dinamic dashboards with SAP BOE platform. I was also challenged to understand and analyze the user requirements and pass them to the back-end team.
      - layout: left
        title: AIRES Project
        # link: None
        # link_text: boringcompany.com
        sub_title: 
        caption: November 2016 - November 2017
        quote: 
          "AIRES: Analisis Inteligente en Redes Sociales" |
          Which means Social Media Intelligent Analysis
        description: | # this will include new lines to allow paragraphs
            Project AIRES was an entrepreneurial team working on Social Media data to exploit it with top edge data science techniques, theories and models. A product was developed with sentiment analysis, user clustering and impact prediction of new posts features. For some time, consulting like projects were done. My role was as a founder and as a member of the dev/technical team.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Austral University
        caption: August 2020 - December 2021
        sub_title: Master of Finance
        # quote: >
        #   Austral University is one of the top three education institutions located on Argentina.
        description: | # this will include new lines to allow paragraphs
          Studying finance was a long-time desire I had. Now I am enjoying the process of doing it.
      - layout: left
        title: Universidad Tecnologica Nacional - Rosario campus
        caption: March 2013 - November 2018
        sub_title: Information System Engineering
        quote: 
          "UTN - Universidad Tecnologica Nacional" |
          Which stands for National Technology University, the statal university from Argentina specialized on technology careers.
        #   Austral University is one of the top three education institutions located on Argentina.
        description: | # this will include new lines to allow paragraphs
          I was lucky to be a student at the UTN, Rosario campus for learning software development, software architecture, technology management and much more. All these in an engineering grade.
      - layout: left
        title: Austral University - Buenos Aires campus
        caption: August 2018 - December 2018
        sub_title: Data Science Postgraduate Course
        # quote: >
        #   Austral University is one of the top three education institutions located on Argentina.
        description: | # this will include new lines to allow paragraphs
          Specializing on the Data Science area for narrowing my career to these kind of challenges/projects.
      - layout: left
        title: Austral University - Rosario campus
        caption: August 2017 - December 2017
        sub_title: Business Intelligence Postgraduate Course
        # quote: >
        #   Austral University is one of the top three education institutions located on Argentina.
        description: | # this will include new lines to allow paragraphs
          Specializing on the BI area for narrowing my career to these kind of challenges/projects.


  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
